import processscheduler as ps
import requests

res = requests.get("https://oneproject-ppe-torus-wus-azsc-000.project.microsoft.com/pss/api/v1.0/projects(msxrm_msdefault.crm.dynamics.com_3269cd33-1ab1-4d17-acd5-5d421693c9b7)/tasks/?$select=gridColor,name,blockDelete,start,finish,duration,index,critical,percentComplete,manual,milestone,outlineLevel,outlineNumber,work,actualWork,remainingWork,bucketId,bucketOrder,summary,notes,durationDisplayFormat,completeThrough,scheduleDrivers,constraintType,constraintDate,collapsed,includeAllCustomFields,cdsPercentComplete,cdsEffortRemaining,cdsEffortCompleted,cdsEffortEstimateAtComplete,cdsScheduleVariance,priority,sprintId,sprintOrder&$expand=parent($select=),conversations($select=teamsConversationId,%20teamsChannelId)",
    headers={
        "accept": "application/json, text/javascript, */*; q=0.01",
        "accept-language": "en-US,en;q=0.9",
        "authority": "oneproject-ppe-torus-wus-azsc-000.project.microsoft.com",
        "authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJmNTM4OTVkMy0wOTVkLTQwOGYtOGU5My04Zjk0YjM5MTQwNGUiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwiaWF0IjoxNjk0NDM3MTIyLCJuYmYiOjE2OTQ0MzcxMjIsImV4cCI6MTY5NDQ0MTY1MSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFZUUFlLzhVQUFBQWNWMU96V3MwT0pQMHpNSmxhMVU3eE1NbGVLeTc4dUNzMkJ4UnlmL1dmejQxbld2eEZOK1o5WFByWjRZU2N1czBEUVViTjdKd3BzYTNjdVRDbGpxNERZN2pqZW96MEZVUTFxV2VGWVpLc0Y2MVZpVEVqNmR0NWNuVjNURVpnZHZtYXdDeVZmd2JXc1FDT3kvMzVjOVd5NE8rbUZ2M2UrYnRQNW9HbkErMStGaz0iLCJhbXIiOlsicnNhIiwibWZhIl0sImFwcGlkIjoiZjUzODk1ZDMtMDk1ZC00MDhmLThlOTMtOGY5NGIzOTE0MDRlIiwiYXBwaWRhY3IiOiIwIiwiZGV2aWNlaWQiOiIyNmU0NjRjMS1iZjQyLTRkYjMtYjBjZS02OWI0MzA3OTU2ZDUiLCJmYW1pbHlfbmFtZSI6IkFsYW0iLCJnaXZlbl9uYW1lIjoiTWQgVGFudmVlciIsImlwYWRkciI6IjI0MDU6MjAxOmE0MDQ6ZjAxNjo1OWM2OmVmYjA6OTM3NzpmZjhlIiwibmFtZSI6Ik1kIFRhbnZlZXIgQWxhbSIsIm9pZCI6IjRiNGNlNTFhLTg0YzAtNDVhNi1hNjQ3LTU4YjM3MWZhYTBkOCIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0yMTQ2NzczMDg1LTkwMzM2MzI4NS03MTkzNDQ3MDctMTEyODMyOSIsInB1aWQiOiIxMDAzQkZGRDgwMUJDQ0NCIiwicmgiOiIwLkFSb0F2NGo1Y3ZHR3IwR1JxeTE4MEJIYlI5T1ZPUFZkQ1k5QWpwT1BsTE9SUUU0YUFKWS4iLCJzY3AiOiJDaGFubmVsLlJlYWRCYXNpYy5BbGwgQ2hhbm5lbFNldHRpbmdzLlJlYWQuQWxsIENoYW5uZWxTZXR0aW5ncy5SZWFkV3JpdGUuQWxsIERpcmVjdG9yeS5SZWFkLkFsbCBEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCBHcm91cC5SZWFkV3JpdGUuQWxsIFBlb3BsZS5SZWFkIFBlb3BsZS5SZWFkLkFsbCBTaXRlcy5SZWFkLkFsbCBUZWFtc0FjdGl2aXR5LlNlbmQgVGVhbXNUYWIuUmVhZC5BbGwgVGVhbXNUYWIuUmVhZFdyaXRlLkFsbCBVbmlmaWVkR3JvdXBNZW1iZXIuUmVhZC5Bc0d1ZXN0IFVzZXIuSW52aXRlLkFsbCBVc2VyLlJlYWRCYXNpYy5BbGwiLCJzdWIiOiJoTmlfS1hVM1FyVU43TmdWUllmNzF2NENseWkwaWZHT0psUHM4RHlPcWVnIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IldXIiwidGlkIjoiNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3IiwidW5pcXVlX25hbWUiOiJtZGFsYW1AbWljcm9zb2Z0LmNvbSIsInVwbiI6Im1kYWxhbUBtaWNyb3NvZnQuY29tIiwidXRpIjoiU1h1SEUzZkhGVWl0SksxOXJIdGlBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il19.AiFOsXJUndYlkaqqLeZaZnTIr7pQGqm3P9ER9_uBET6cBsV43f9Ka-FZ3Y4tm-mISvhXP2uAlGLZvxm-5GGBR6YRBhs25-gk9wRp6Q5VfGS2vdg6Rwy-sYbOaEdv0HxMzGydXHZEG1jvMcTEL3j5m1V8gxGUilWNOTTt0t2Ac9ES_HC1464q7XxdkyhjOjQmBkO27wFbkdgVHxNuys-dKIKDKV7NGBdzIo_OsrLdo5Cgmr1zboNZ8sYfF4OQBD7-hDkF-ow_stek7xbIyHioXzaoXNUSUDFzFDzzuZWiytNYuwPOQGWi7LoEDDzGsEF0ZZtvGDwwRTdFaxc192s5JA",
        "content-type": "application/json",
        "origin": "https://portfolios.officeppe.com",
        "referer": "https://portfolios.officeppe.com/",
        "sec-ch-ua": "\"Chromium\";v=\"116\", \"Not)A;Brand\";v=\"24\", \"Microsoft Edge\";v=\"116\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69",
        "viewportdefinition": "{\"selects\":[\"/project/tasks?$select=gridColor,name,blockDelete,start,finish,duration,index,critical,percentComplete,manual,milestone,outlineLevel,outlineNumber,work,actualWork,remainingWork,bucketId,bucketOrder,summary,notes,durationDisplayFormat,completeThrough,scheduleDrivers,constraintType,constraintDate,collapsed,includeAllCustomFields,cdsPercentComplete,cdsEffortRemaining,cdsEffortCompleted,cdsEffortEstimateAtComplete,cdsScheduleVariance,priority,sprintId,sprintOrder&$expand=assignments($select=taskId,percentWorkComplete,resourceId&$expand=resource($select=name,bookableResourceId,userPrincipalName,generic)),predecessors,successors,parent($select=),conversations($select=teamsConversationId, teamsChannelId)\",\"/project/tasks/fields?$select=name,type,rollup&$expand=values\",\"/project/links?$select=driver,predecessorId,successorId,linkType,delay,delayUnits\",\"/project?$select=name,percentComplete,workTemplateId,projectStart,hoursPerDay,duration,hoursPerWeek,daysPerMonth,latestTaskFinish,calendarId,hasCustomCalendar,ignoreResourceCalendars,earliestTaskStart,durationInDays,work,actualWork,remainingWork,taskDefaultFinishTime,taskDefaultStartTime,timezoneName,timezoneOffset,timezone,officeGroupId,projectState,projectManagerAadId,defaultSprintCreated\",\"/project/conditionalColoringRules\",\"/project/attachments?$select=taskId,uri,name,type,showOnCard\",\"/project/checklistItems?$select=taskId,name,completed,order\",\"/project/buckets?$select=name,order,color\",\"/project/sprints\",\"/project/views/grid\",\"/project/resources?$select=name,bookableResourceId,userPrincipalName,generic,aadId,jobTitle,type,aadUserType\",\"/project/labels\",\"/project/labelassociations\",\"/project/goals\",\"/project/goalAssociations\"]}",
        "x-project-client-type": "ModernProjectFamily",
        "x-project-sessiontoken": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc1Qzk0RjQxQjA3NkMxMDExQzdGRTZBMDY4NkZFRUVGQUM1NTE1MEIiLCJ4NXQiOiJkY2xQUWJCMndRRWNmLWFnYUdfdTc2eFZGUXMiLCJ0eXAiOiJKV1QifQ.eyJwcm9qZWN0UGVybWlzc2lvbiI6IntcInByb2plY3RJZFwiOlwibXN4cm1fbXNkZWZhdWx0LmNybS5keW5hbWljcy5jb21fMzI2OWNkMzMtMWFiMS00ZDE3LWFjZDUtNWQ0MjE2OTNjOWI3XCIsXCJhY2Nlc3NSaWdodHNcIjpcIlJlYWQsV3JpdGUsQXBwZW5kLEFwcGVuZFRvLENyZWF0ZSxEZWxldGVcIixcImFjY2Vzc1JpZ2h0c0Jhc2VkT25DZHNQZXJtaXNzaW9uXCI6XCJSZWFkLFdyaXRlLEFwcGVuZCxBcHBlbmRUbyxDcmVhdGUsRGVsZXRlXCJ9IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS9pZGVudGl0eS9jbGFpbXMvb2JqZWN0aWRlbnRpZmllciI6IjRiNGNlNTFhLTg0YzAtNDVhNi1hNjQ3LTU4YjM3MWZhYTBkOCIsInRpZCI6IjcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0NyIsImV4cCI6MTY5NDQzOTIyN30.syQnWGiepRIQeYBwyflyCO47ZuOtjx4LTxAdRYjolUqyO8uB84hWPO-_PQ984k41G4e-vXH5MEq2tbIzdnkgRTBSnjIixTkWkAoqZXlYrXQ51Gf_-BYoRCktRUrQ0eus6-AetwA90ugjO5rh5o0vtQwEXajdkVH-zZugP9WfpZzhj3BkJcpboxgbUSYmszyDEworp299rqvTjz-_XCqeVkkhfQspJSkccPxNT0bXr9slC0xt_TT1u34ztLUYYIds0FuITxLKnRH_vou6JT71uuP4VZOVUWSXxlTVC-Q8YdpMb-4uoaS6kASopOU_s1hdP3-G_-LrZ_ufP3lu8tVbow"
    },
    cookies={},
    auth=(),
)

tasks = res.json()
